# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datee', models.DateField(auto_now=True)),
                ('timee', models.TimeField(auto_now=True)),
                ('task', models.TextField(max_length=5000)),
                ('status', models.CharField(choices=[('p', 'pending'), ('d', 'done'), ('m', 'missed')], default='Pending', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userappointments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='app1.User')),
            ],
        ),
    ]
